name: Build Beyond Borders App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Expo CLI
      run: npm install -g @expo/cli

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EAS_TOKEN }}

    - name: Build Android App
      run: eas build --platform android --profile preview --non-interactive

    - name: Build iOS App
      run: eas build --platform ios --profile preview --non-interactive
